<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../TaskFlow.Infrastructure/TaskFlow.Infrastructure.csproj" />
    <EmbeddedResource Include="../../docs/deployment/runtime-permissions.sql" LogicalName="RuntimePermissions.sql" />
  </ItemGroup>
</Project>
